# Generated by Django 5.2.8 on 2025-11-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Product Title",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Color"
                    ),
                ),
                (
                    "memory",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Memory Capacity",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Manufacturer",
                    ),
                ),
                (
                    "regular_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Regular Price",
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Sale Price",
                    ),
                ),
                (
                    "photos",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Product Photos"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Product Code",
                    ),
                ),
                (
                    "review_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Review Count"
                    ),
                ),
                (
                    "screen_diagonal",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Diagonal"
                    ),
                ),
                (
                    "screen_resolution",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Screen Resolution",
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Specifications"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Date"),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "products",
            },
        ),
    ]
